### ISSUE TITLE
Missing file start_end_task.yaml

### ISSUE THREAD

**Issue by mbreuss** [ErickRosete/tacorl#1]
Hi,

thanks for the sharing the great codebase! 
I tried to start a training but got a problem with mentioned a file in the rollout callback ```config/callbacks/rollout/default.yaml```:

```yaml
...
start_end_tasks: ~/tacorl/calvin/start_end_tasks.json
...
```
I have already installed calvin, however I cannot fine this file there. Is it located somewhere else?

Another general question regarding the calvin paths mentioned in the configs: 
After running the ```install.sh``` script, I have the calvin_env located in ```taco_rl/dependencies/calvin_env```. In several configs the relative path to calvin is often called by ```~/tacorl/calvin/```. Should this be changed to the dependency subfolder or am I missing somethere here?
Thanks in advance.

**Comment by ErickRosete** [comment]
Thank your for your interest in our repository.
I will add a slightly modified calvin dataset in the following days to the kaggle webpage, this will include the required `start_end_tasks.json` which is used to be able to evaluate the model in `calvin_env` while training.

Regarding the second question the default data_dir is`~/tacorl/calvin/` this is the directory where we are assuming you stored the dataset, but this can be easily overwritten when running training as shown in the README.md. On the otherhand `tacorl/dependencies/calvin_env` is the `calvin_env` repository path, we are installing it as a package so we import it directly with `import calvin_env`.

**Comment by mbreuss** [comment]
Thanks for the answer. Looking forward to the updated data. I will close the issue.

**Comment by tunglm2203** [comment]
Hi @ErickRosete , 
I downloaded the dataset from kaggle, but I only found 4 JSON files as follows:
 - dataset-metadata.json    
 - split.json
 - nn_steps_from_step.json  
 - splitOLD.json

Did you upload "start_end_tasks.json" to kaggle webpage?

Additionally, I found that training with simulation also requires "start_end_tasks.json", could you share that file?

Thanks in advance.
