### ISSUE TITLE
Missing folder src/tacorl/networks.representation

### ISSUE THREAD

**Issue by mbreuss** [ErickRosete/tacorl#2]
Hi,

I think there is a missing folder called ```/src/tacorl/networks/representation```, which is needed for all the perceptual embeddings. Would it be possible to add it?
Thanks in advance.

**Comment by ErickRosete** [comment]
Sure, I just added the code, let me know if you need anything else.

**Comment by mbreuss** [comment]
Thanks for the quick fix! I think there is another file missing called: ```tacorl/modules/representation_learning/representation_lightning.py```
It gets imported in https://github.com/ErickRosete/tacorl/blob/master/src/tacorl/utils/networks.py#L9

**Comment by mbreuss** [comment]
Solved with the recent commit e7da7c2.
